[build]
# Build in release mode.
release = false

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["../../frontend", "../../api"]

[serve]
# The address to serve on.
addr = "127.0.0.1"
# The port to serve on.
port = 8900
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false